version: '3'
services:
  postgres:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME_DEVELOPMENT}
    ports:
      - 5431:5432
    tty: true
    volumes:
      - pgdata:/var/lib/postgresql/data
  nestjs:
    container_name: nest-app
    build:
      context: .
    command: npm run start:dev
    environment:
      - DB_TYPE=${DB_DIALECT}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - POSTGRES_DB=${DB_NAME_DEVELOPMENT}
      - POSTGRES_SYNC=false
      - JWT_SECRET=${JWTKEY}
      - POSTGRES_PORT=${DB_PORT}
      - APP_EXPIRES=${APP_EXPIRES}
      - APP_PORT=${APP_PORT}
    ports:
      - 3000:3000
    depends_on:
      - postgres
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/node_modules/bcryptjs/
  minio:
    container_name: minio
    image: docker.io/bitnami/minio:2022
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio124
    volumes:
      - 'minio_data:/data'
volumes:
  pgdata:
  minio_data:
    driver: local
